using System.Reflection;
using System.Runtime.CompilerServices;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace MockInterceptor.Generator.Tests;

public partial class MockInterceptorGeneratorTests
{
    private static CSharpCompilation CreateCompilation(string source, CSharpParseOptions? parseOptions = null)
    {
        parseOptions ??= CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview);
        var syntaxTree = CSharpSyntaxTree.ParseText(source, parseOptions);

        var references = new[]
        {
            MetadataReference.CreateFromFile(typeof(Binder).GetTypeInfo().Assembly.Location)
        };

        return CSharpCompilation.Create(
            "MockInterceptorGeneratorTests",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static (CSharpCompilation Compilation, GeneratorDriverRunResult RunResult) RunGenerator(string source)
    {
        var parseOptions = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview);
        var compilation  = CreateCompilation(source, parseOptions);
        var generator    = new MockInterceptorGenerator();

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [generator.AsSourceGenerator()],
            parseOptions: parseOptions);

        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out _,
            out var diagnostics);

        Assert.All(diagnostics, d => Assert.NotEqual(DiagnosticSeverity.Error, d.Severity));

        var runResult = driver.GetRunResult();

        Assert.All(runResult.Diagnostics, d => Assert.NotEqual(DiagnosticSeverity.Error, d.Severity));

        return (compilation, runResult);
    }

    private static void AssertEqual(SourceGenerated[] expected, SourceGenerated[] actual, [CallerFilePath] string? caller = null)
    {
        Assert.Equal(expected.Length, actual.Length);

        var i = 0;

        var expectedContent = "";
        var actualContent = "";

        try
        {
            for (; i < expected.Length; i++)
            {
                Assert.Equal(expected[i].Path, actual[i].Path);
                Assert.Equal(
                    expectedContent = expected[i].Content.SanitizeInterceptionData(),
                    actualContent   = actual[i].Content.SanitizeInterceptionData()
                );
            }
        }
        catch
        {
            var directory = Path.Join(Path.GetDirectoryName(caller), ".debug");

            if (Directory.Exists(directory))
            {
                Directory.Delete(directory, true);
            }

            Directory.CreateDirectory(directory);

            File.WriteAllText(Path.Join(directory, $"{expected[i].Path}.expected.{i}.txt"), expectedContent);
            File.WriteAllText(Path.Join(directory, $"{actual[i].Path}.actual.{i}.txt"),     actualContent);

            throw;
        }
    }

    [Fact]
    public void EmptySource()
    {
        const string SOURCE = "";

        var actual = RunGenerator(SOURCE).RunResult.GeneratedTrees.GetAllEntries();

        SourceGenerated[] expected =
        [
            new(
                "Microsoft.CodeAnalysis.EmbeddedAttribute.cs",
                """
                // <auto-generated/>
                namespace Microsoft.CodeAnalysis
                {
                    internal sealed partial class EmbeddedAttribute : global::System.Attribute
                    {
                    }
                }
                """
            ),
            new(
                "InterceptsLocationAttribute.g.cs",
                """
                namespace System.Runtime.CompilerServices;

                #pragma warning disable CS9113

                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                public sealed class InterceptsLocationAttribute(global::System.Int32 version, global::System.String data) : global::System.Attribute;
                """
            ),
            new(
                "InterceptAttribute.g.cs",
                """
                namespace MockInterceptor;

                #pragma warning disable CS9113

                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
                internal sealed class InterceptAttribute(global::System.Type type) : global::System.Attribute;
                """
            ),
        ];

        AssertEqual(expected, actual);
    }

    [Theory]
    [MemberData(nameof(Scenarios.Valid), MemberType = typeof(Scenarios))]
    public void ValidGeneratation(ValidScenario scenario)
    {
        if (scenario.Skip)
        {
            Assert.Skip("Skipped Scenario");

            return;
        }

        var actual = RunGenerator(scenario.Source).RunResult.GeneratedTrees.GetInterceptors();

        AssertEqual(scenario.Expected, actual);
    }
}
