#pragma warning disable IL3000

using System.Diagnostics.CodeAnalysis;

namespace MockInterceptor.Generator.Tests;

public partial class MockInterceptorGeneratorTests
{
    public record ValidScenario
    {
        public required string            Source   { get; init; }
        public required SourceGenerated[] Expected { get; init; }
        public required bool              Skip     { get; init; }
    }

    public static class Scenarios
    {
        private const bool SKIP = false;

        private static readonly ValidScenario[] valid =
        [
            new()
            {
                Source =
                    """
                    [assembly: MockInterceptor.Intercept(typeof(Provider.Executor))]

                    using System;

                    namespace Consumer
                    {
                        using Provider;

                        public class Worker;
                    }

                    namespace Provider
                    {
                        public class Executor;
                    }
                    """,
                Expected = [],
                Skip     = SKIP,
            },
            new()
            {
                Source =
                """
                [assembly: MockInterceptor.Intercept(typeof(Provider.Executor))]

                using System;

                namespace Consumer
                {
                    using Provider;

                    public class Worker
                    {
                        public int DoWork()
                        {
                            Console.WriteLine(Executor.GetVersion());

                            var executor = new Executor();
                            var sum = executor.Execute();
                            sum += executor.Execute();
                            return sum;
                        }
                    }
                }

                namespace Provider
                {
                    public class Executor
                    {
                        public static string GetVersion() => "v1";
                        public int Execute() => 42;
                    }
                }
                """,
                Expected =
                [
                    new()
                    {
                        Path    = "ExecutorInterceptor.g.cs",
                        Content =
                            """
                            #if TEST
                            // <auto-generated/>
                            #nullable enable
                            using System.Collections.Concurrent;
                            using System.Runtime.CompilerServices;

                            namespace MockInterceptor.Interceptors;

                            internal interface IExecutor
                            {
                                global::System.Int32 Execute();
                            }

                            internal interface IStaticExecutor
                            {
                                global::System.String GetVersion();
                            }

                            internal static class ExecutorInterceptor
                            {
                                private static readonly ConcurrentDictionary<global::Provider.Executor, IExecutor> mocks = [];

                                public static ConcurrentQueue<IExecutor> MockQueue { get; } = [];
                                public static IStaticExecutor? StaticMock { get; set; }

                                public static void Reset()
                                {
                                    mocks.Clear();
                                    MockQueue.Clear();
                                    StaticMock = null;
                                }

                                public static bool TryGetOrTrackMock(global::Provider.Executor instance, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out IExecutor? mock)
                                {
                                    if (mocks.TryGetValue(instance, out mock))
                                    {
                                        return true;
                                    }

                                    if (MockQueue.TryDequeue(out mock))
                                    {
                                        mocks[instance] = mock;
                                        return true;
                                    }

                                    mock = null;
                                    return false;
                                }

                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                public static global::System.String GetVersion() =>
                                    StaticMock != null
                                        ? StaticMock.GetVersion()
                                        : global::Provider.Executor.GetVersion();

                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                public static global::System.Int32 Execute(this global::Provider.Executor instance) =>
                                    TryGetOrTrackMock(instance, out var mock)
                                        ? mock.Execute()
                                        : instance.Execute();
                            }
                            #endif

                            """,
                    }
                ],
                Skip     = SKIP,
            },
            new()
            {
                Source =
                """
                [assembly: MockInterceptor.Intercept(typeof(Provider.Executor))]

                using System;

                namespace Consumer
                {
                    using Provider;

                    public class Worker
                    {
                        public (int, string) DoWork()
                        {
                            var executor = new Executor();

                            return (executor.Execute(), Executor.GetVersion());
                        }
                    }
                }

                namespace Provider
                {
                    public class Executor
                    {
                        public static string GetVersion() => "v1";
                        public int Execute() => 42;
                    }
                }
                """,
                Expected =
                [
                    new()
                    {
                        Path    = "ExecutorInterceptor.g.cs",
                        Content =
                            """
                            #if TEST
                            // <auto-generated/>
                            #nullable enable
                            using System.Collections.Concurrent;
                            using System.Runtime.CompilerServices;

                            namespace MockInterceptor.Interceptors;

                            internal interface IExecutor
                            {
                                global::System.Int32 Execute();
                            }

                            internal interface IStaticExecutor
                            {
                                global::System.String GetVersion();
                            }

                            internal static class ExecutorInterceptor
                            {
                                private static readonly ConcurrentDictionary<global::Provider.Executor, IExecutor> mocks = [];

                                public static ConcurrentQueue<IExecutor> MockQueue { get; } = [];
                                public static IStaticExecutor? StaticMock { get; set; }

                                public static void Reset()
                                {
                                    mocks.Clear();
                                    MockQueue.Clear();
                                    StaticMock = null;
                                }

                                public static bool TryGetOrTrackMock(global::Provider.Executor instance, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out IExecutor? mock)
                                {
                                    if (mocks.TryGetValue(instance, out mock))
                                    {
                                        return true;
                                    }

                                    if (MockQueue.TryDequeue(out mock))
                                    {
                                        mocks[instance] = mock;
                                        return true;
                                    }

                                    mock = null;
                                    return false;
                                }

                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                public static global::System.Int32 Execute(this global::Provider.Executor instance) =>
                                    TryGetOrTrackMock(instance, out var mock)
                                        ? mock.Execute()
                                        : instance.Execute();

                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                public static global::System.String GetVersion() =>
                                    StaticMock != null
                                        ? StaticMock.GetVersion()
                                        : global::Provider.Executor.GetVersion();
                            }
                            #endif

                            """,
                    }
                ],
                Skip = SKIP,
            },
            new()
            {
                Source =
                    """
                    [assembly: MockInterceptor.Intercept(typeof(Provider.Executor))]

                    using System;

                    namespace Consumer
                    {
                        using Provider;

                        public class Worker
                        {
                            public int DoWork()
                            {
                                Console.WriteLine(Executor.GetVersion());

                                var executor = new Executor();
                                var sum = executor.Execute();
                                sum += executor.Execute();
                                return sum;
                            }
                        }
                    }

                    namespace Provider
                    {
                        public class Executor
                        {
                            public static string GetVersion() => "v1";
                            public int Execute() => 42;
                        }
                    }
                    """,
                Expected =
                [
                    new()
                    {
                        Path = "ExecutorInterceptor.g.cs",
                        Content =
                            """
                            #if TEST
                            // <auto-generated/>
                            #nullable enable
                            using System.Collections.Concurrent;
                            using System.Runtime.CompilerServices;

                            namespace MockInterceptor.Interceptors;

                            internal interface IExecutor
                            {
                                global::System.Int32 Execute();
                            }

                            internal interface IStaticExecutor
                            {
                                global::System.String GetVersion();
                            }

                            internal static class ExecutorInterceptor
                            {
                                private static readonly ConcurrentDictionary<global::Provider.Executor, IExecutor> mocks = [];

                                public static ConcurrentQueue<IExecutor> MockQueue { get; } = [];
                                public static IStaticExecutor? StaticMock { get; set; }

                                public static void Reset()
                                {
                                    mocks.Clear();
                                    MockQueue.Clear();
                                    StaticMock = null;
                                }

                                public static bool TryGetOrTrackMock(global::Provider.Executor instance, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out IExecutor? mock)
                                {
                                    if (mocks.TryGetValue(instance, out mock))
                                    {
                                        return true;
                                    }

                                    if (MockQueue.TryDequeue(out mock))
                                    {
                                        mocks[instance] = mock;
                                        return true;
                                    }

                                    mock = null;
                                    return false;
                                }

                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                public static global::System.String GetVersion() =>
                                    StaticMock != null
                                        ? StaticMock.GetVersion()
                                        : global::Provider.Executor.GetVersion();

                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                public static global::System.Int32 Execute(this global::Provider.Executor instance) =>
                                    TryGetOrTrackMock(instance, out var mock)
                                        ? mock.Execute()
                                        : instance.Execute();
                            }
                            #endif

                            """
                    }
                ],
                Skip = SKIP,
            },
            new()
            {
                Source =
                    """
                    [assembly: MockInterceptor.Intercept(typeof(Provider.Executor))]

                    using System;

                    namespace Consumer
                    {
                        using Provider;

                        public class Worker
                        {
                            public int DoWork()
                            {
                                Console.WriteLine(Executor.GetVersion());

                                return 0;
                            }
                        }
                    }

                    namespace Provider
                    {
                        public class Executor
                        {
                            public static string GetVersion() => "v1";
                        }
                    }
                    """,
                Expected =
                [
                    new()
                    {
                        Path    = "ExecutorInterceptor.g.cs",
                        Content = """
                            #if TEST
                            // <auto-generated/>
                            #nullable enable
                            using System.Collections.Concurrent;
                            using System.Runtime.CompilerServices;

                            namespace MockInterceptor.Interceptors;

                            internal interface IStaticExecutor
                            {
                                global::System.String GetVersion();
                            }

                            internal static class ExecutorInterceptor
                            {
                                public static IStaticExecutor? StaticMock { get; set; }

                                public static void Reset()
                                {
                                    StaticMock = null;
                                }

                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...+wL/Xn44rZuMAAAA")]
                                public static global::System.String GetVersion() =>
                                    StaticMock != null
                                        ? StaticMock.GetVersion()
                                        : global::Provider.Executor.GetVersion();
                            }
                            #endif

                            """
                    }
                ],
                Skip = SKIP,
            },
            new()
            {
                Source =
                    """
                    [assembly: MockInterceptor.Intercept(typeof(Provider.Executor))]

                    using System;

                    namespace Consumer
                    {
                        using Provider;

                        public class Worker
                        {
                            public int DoWork()
                            {
                                var executor = new Executor();
                                var sum = executor.Execute();
                                sum += executor.Execute();
                                return sum;
                            }
                        }
                    }

                    namespace Provider
                    {
                        public class Executor
                        {
                            public int Execute() => 42;
                        }
                    }
                    """,
                Expected =
                [
                    new()
                    {
                        Path    = "ExecutorInterceptor.g.cs",
                        Content =
                            """
                            #if TEST
                            // <auto-generated/>
                            #nullable enable
                            using System.Collections.Concurrent;
                            using System.Runtime.CompilerServices;

                            namespace MockInterceptor.Interceptors;

                            internal interface IExecutor
                            {
                                global::System.Int32 Execute();
                            }

                            internal static class ExecutorInterceptor
                            {
                                private static readonly ConcurrentDictionary<global::Provider.Executor, IExecutor> mocks = [];

                                public static ConcurrentQueue<IExecutor> MockQueue { get; } = [];

                                public static void Reset()
                                {
                                    mocks.Clear();
                                    MockQueue.Clear();
                                }

                                public static bool TryGetOrTrackMock(global::Provider.Executor instance, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out IExecutor? mock)
                                {
                                    if (mocks.TryGetValue(instance, out mock))
                                    {
                                        return true;
                                    }

                                    if (MockQueue.TryDequeue(out mock))
                                    {
                                        mocks[instance] = mock;
                                        return true;
                                    }

                                    mock = null;
                                    return false;
                                }

                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                public static global::System.Int32 Execute(this global::Provider.Executor instance) =>
                                    TryGetOrTrackMock(instance, out var mock)
                                        ? mock.Execute()
                                        : instance.Execute();
                            }
                            #endif

                            """
                    }
                ],
                Skip = SKIP,
            },
            new()
            {
                Source =
                    """
                    [assembly: MockInterceptor.Intercept(typeof(Provider.Executor))]

                    using System;

                    namespace Consumer
                    {
                        using Provider;

                        public class Worker
                        {
                            public int DoWork()
                            {
                                var executor = new Executor();

                                var value = 1;

                                return executor.Execute(&value);
                            }
                        }
                    }

                    namespace Provider
                    {
                        public class Executor
                        {
                            public unsafe int Execute(int* value) => *value + 1;
                        }
                    }
                    """,
                Expected =
                [
                    new()
                    {
                        Path    = "ExecutorInterceptor.g.cs",
                        Content =
                            """
                            #if TEST
                            // <auto-generated/>
                            #nullable enable
                            using System.Collections.Concurrent;
                            using System.Runtime.CompilerServices;

                            namespace MockInterceptor.Interceptors;

                            internal interface IExecutor
                            {
                                unsafe global::System.Int32 Execute(global::System.Int32* value);
                            }

                            internal static class ExecutorInterceptor
                            {
                                private static readonly ConcurrentDictionary<global::Provider.Executor, IExecutor> mocks = [];

                                public static ConcurrentQueue<IExecutor> MockQueue { get; } = [];

                                public static void Reset()
                                {
                                    mocks.Clear();
                                    MockQueue.Clear();
                                }

                                public static bool TryGetOrTrackMock(global::Provider.Executor instance, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out IExecutor? mock)
                                {
                                    if (mocks.TryGetValue(instance, out mock))
                                    {
                                        return true;
                                    }

                                    if (MockQueue.TryDequeue(out mock))
                                    {
                                        mocks[instance] = mock;
                                        return true;
                                    }

                                    mock = null;
                                    return false;
                                }

                                [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                                public unsafe static global::System.Int32 Execute(this global::Provider.Executor instance, global::System.Int32* value) =>
                                    TryGetOrTrackMock(instance, out var mock)
                                        ? mock.Execute(value)
                                        : instance.Execute(value);
                            }
                            #endif

                            """
                    }
                ],
                Skip = SKIP,
            },
            new()
            {
                Source =
                    """
                    [assembly: MockInterceptor.Intercept(typeof(Provider.Executor))]
                    using System;

                    namespace Consumer
                    {
                        using Provider;

                        public class Worker
                        {
                            public int Execute()
                            {
                                var executor = new Executor<int>();

                                return executor.Execute(1);
                            }
                        }
                    }

                    namespace Provider
                    {
                        public class Executor<T>
                        {
                            public T Execute(T value) => value;
                        }
                    }
                    """,
                Expected = [],
                Skip     = SKIP,
            },
            new()
            {
                Source =
                    """
                    [assembly: MockInterceptor.Intercept(typeof(Provider.Executor<int>))]
                    using System;

                    namespace Consumer
                    {
                        using Provider;

                        public class Worker
                        {
                            public int Execute()
                            {
                                var executor = new Executor<int>();

                                return executor.Execute(1);
                            }
                        }
                    }

                    namespace Provider
                    {
                        public class Executor<T>
                        {
                            public T Execute(T value) => value;
                        }
                    }
                    """,
                Expected =
                [
                    new()
                    {
                        Path    = "ExecutorInt32Interceptor.g.cs",
                        Content =
                        """
                        #if TEST
                        // <auto-generated/>
                        #nullable enable
                        using System.Collections.Concurrent;
                        using System.Runtime.CompilerServices;

                        namespace MockInterceptor.Interceptors;

                        internal interface IExecutorInt32
                        {
                            global::System.Int32 Execute(global::System.Int32 value);
                        }

                        internal static class ExecutorInt32Interceptor
                        {
                            private static readonly ConcurrentDictionary<global::Provider.Executor<global::System.Int32>, IExecutorInt32> mocks = [];

                            public static ConcurrentQueue<IExecutorInt32> MockQueue { get; } = [];

                            public static void Reset()
                            {
                                mocks.Clear();
                                MockQueue.Clear();
                            }

                            public static bool TryGetOrTrackMock(global::Provider.Executor<global::System.Int32> instance, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out IExecutorInt32? mock)
                            {
                                if (mocks.TryGetValue(instance, out mock))
                                {
                                    return true;
                                }

                                if (MockQueue.TryDequeue(out mock))
                                {
                                    mocks[instance] = mock;
                                    return true;
                                }

                                mock = null;
                                return false;
                            }

                            [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                            public static global::System.Int32 Execute(this global::Provider.Executor<global::System.Int32> instance, global::System.Int32 value) =>
                                TryGetOrTrackMock(instance, out var mock)
                                    ? mock.Execute(value)
                                    : instance.Execute(value);
                        }
                        #endif

                        """,
                    }
                ],
                Skip = SKIP,
            },
            new()
            {
                Source =
                    """
                    [assembly: MockInterceptor.Intercept(typeof(Provider.Executor<int>.Job))]

                    using System;

                    namespace Consumer
                    {
                        using Provider;

                        public class Worker
                        {
                            public int Execute()
                            {
                                var job = new Executor<int>.Job();

                                return job.Execute(1);
                            }
                        }
                    }

                    namespace Provider
                    {
                        public class Executor<T>
                        {
                            public class Job
                            {
                                public T Execute(T value) => value;
                            }
                        }
                    }
                    """,
                Expected =
                [
                    new()
                    {
                        Path    = "ExecutorInt32JobInterceptor.g.cs",
                        Content =
                        """
                        #if TEST
                        // <auto-generated/>
                        #nullable enable
                        using System.Collections.Concurrent;
                        using System.Runtime.CompilerServices;

                        namespace MockInterceptor.Interceptors;

                        internal interface IExecutorInt32Job
                        {
                            global::System.Int32 Execute(global::System.Int32 value);
                        }

                        internal static class ExecutorInt32JobInterceptor
                        {
                            private static readonly ConcurrentDictionary<global::Provider.Executor<global::System.Int32>.Job, IExecutorInt32Job> mocks = [];

                            public static ConcurrentQueue<IExecutorInt32Job> MockQueue { get; } = [];

                            public static void Reset()
                            {
                                mocks.Clear();
                                MockQueue.Clear();
                            }

                            public static bool TryGetOrTrackMock(global::Provider.Executor<global::System.Int32>.Job instance, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out IExecutorInt32Job? mock)
                            {
                                if (mocks.TryGetValue(instance, out mock))
                                {
                                    return true;
                                }

                                if (MockQueue.TryDequeue(out mock))
                                {
                                    mocks[instance] = mock;
                                    return true;
                                }

                                mock = null;
                                return false;
                            }

                            [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "...")]
                            public static global::System.Int32 Execute(this global::Provider.Executor<global::System.Int32>.Job instance, global::System.Int32 value) =>
                                TryGetOrTrackMock(instance, out var mock)
                                    ? mock.Execute(value)
                                    : instance.Execute(value);
                        }
                        #endif

                        """,
                    }
                ],
                Skip = SKIP,
            },
            new()
            {
                Source =
                    """
                    [assembly: MockInterceptor.Intercept(typeof(Provider.Executor<int>.Job<string>))]

                    using System;

                    namespace Consumer
                    {
                        using Provider;

                        public class Worker
                        {
                            public int Execute()
                            {
                                var job = new Executor<int>.Job<string>();

                                return job.Execute("v1");
                            }
                        }
                    }

                    namespace Provider
                    {
                        public class Executor<T>
                        {
                            public class Job<U>
                            {
                                public T Execute(U value) => throw new NotImplementedException();
                            }
                        }
                    }
                    """,
                Expected =
                [
                    new()
                    {
                        Path    = "ExecutorInt32JobStringInterceptor.g.cs",
                        Content =
                        """
                        #if TEST
                        // <auto-generated/>
                        #nullable enable
                        using System.Collections.Concurrent;
                        using System.Runtime.CompilerServices;

                        namespace MockInterceptor.Interceptors;

                        internal interface IExecutorInt32JobString
                        {
                            global::System.Int32 Execute(global::System.String value);
                        }

                        internal static class ExecutorInt32JobStringInterceptor
                        {
                            private static readonly ConcurrentDictionary<global::Provider.Executor<global::System.Int32>.Job<global::System.String>, IExecutorInt32JobString> mocks = [];

                            public static ConcurrentQueue<IExecutorInt32JobString> MockQueue { get; } = [];

                            public static void Reset()
                            {
                                mocks.Clear();
                                MockQueue.Clear();
                            }

                            public static bool TryGetOrTrackMock(global::Provider.Executor<global::System.Int32>.Job<global::System.String> instance, [global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out IExecutorInt32JobString? mock)
                            {
                                if (mocks.TryGetValue(instance, out mock))
                                {
                                    return true;
                                }

                                if (MockQueue.TryDequeue(out mock))
                                {
                                    mocks[instance] = mock;
                                    return true;
                                }

                                mock = null;
                                return false;
                            }

                            [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, ".../gd0RM/cCYBAAA")]
                            public static global::System.Int32 Execute(this global::Provider.Executor<global::System.Int32>.Job<global::System.String> instance, global::System.String value) =>
                                TryGetOrTrackMock(instance, out var mock)
                                    ? mock.Execute(value)
                                    : instance.Execute(value);
                        }
                        #endif

                        """,
                    }
                ],
                Skip = SKIP,
            },
        ];

        public static TheoryData<ValidScenario> Valid => [.. valid];
    }
}
